### ISSUE TITLE
[AVM Module Issue]: location should be specified as a variable not inferred from a resource group data source

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-routetable#15]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

the location should not be inferred using a data source , ref;

https://github.com/Azure/Azure-Verified-Modules/issues/313#issuecomment-2010359818

& 

https://www.youtube.com/watch?v=l8k_cOHep28

**Comment by adammontlake** [comment]
Yup, that is a good point, will update the module.
I will add this as a coalesce(input_location, data.resource_group.location, null) - for backwards compatibility.

**Comment by adammontlake** [comment]
Turns out the linting standards of AVM do not allow for null valued location, adding it as a mandatory variable.
[PR](https://github.com/Azure/terraform-azurerm-avm-res-network-routetable/pull/18) raised and waiting for review.
