### ISSUE TITLE
[AVM Module Issue]: var.routes should be a map not a list?

### ISSUE THREAD

**Issue by kewalaka** [Azure/terraform-azurerm-avm-res-network-routetable#16]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### Description

As per this video; https://www.youtube.com/watch?v=Bat0sY06jz4

Lists have a position index rather than a named one.  If you remove an item from the middle of the list, the position of other items gets changed, leading them to be dropped and re-created.

I think the routes should be supplied as a `map`, not a `list`

**Comment by adammontlake** [comment]
Thanks @kewalaka you are correct, according to TFNFR7 I should be using maps as the type and not convert the list to map during deployment.
This is addressed in [PR](https://github.com/Azure/terraform-azurerm-avm-res-network-routetable/pull/18)
PR raised and waiting for review.
