### ISSUE TITLE
[AVM Module Issue]: Deprecated variable

### ISSUE THREAD

**Issue by jaredfholgate** [Azure/terraform-azurerm-avm-res-network-routetable#34]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

latest

### Description

When using the module with recent version so the azurerm provider we get this warning:

```
│ Warning: Argument is deprecated
│
│   with module.hubnetworks[0].module.hub_routing["hub"].azurerm_route_table.this,
│   on .terraform\modules\hubnetworks.hub_routing\main.tf line 6, in resource "azurerm_route_table" "this":
│    6:   disable_bgp_route_propagation = var.disable_bgp_route_propagation
│
│ The property `disable_bgp_route_propagation` has been superseded by the property `bgp_route_propagation_enabled` and will be removed in v4.0 of the AzureRM Provider.  
╵
```

**Comment by adammontlake** [comment]
Thanks for the bug @jaredfholgate
Your probably using version 2.2 of the module, which also limits the provider version to a version that uses the old interface.
Please update to module version 0.3.0

Let me know if you hit any more issues!
