### ISSUE TITLE
[AVM Module Issue]:  terraform plan -refresh-only fails when called before resources are deployed

### ISSUE THREAD

**Issue by yrachakonda** [Azure/terraform-azurerm-avm-res-network-routetable#44]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.3.1

### Description

We are using Azure DevOps to deploy our Azure resources. Our pipeline always calls  terraform plan -refresh-only before performing a terraform plan and apply steps. We have had issues with the tfstate file not staying sync with the deployments and this was our workaround. The solution works perfectly for all our remaining pipelines but fails for the AVM route table module. We use AVM modules extensively in our IaC. Here are the details of the actual error we are encountering:

**terraform plan -var-file="..\..\environments\variables.dev_002.tfvars" -input=false -out=tfplan**

Planning failed. Terraform encountered an error while generating this plan.
 ╷
│ Error: Error in function call
│
│   on .terraform\modules\route_table.azure_route_table\outputs.tf line 18, in output "routes":
│   18:   value = zipmap(
│   19:     [for route in var.routes : route.name],
│   20:     values(azurerm_route.this)[*]
│   21:   )
│     ├────────────────
│     │ while calling zipmap(keys, values)
│     │ azurerm_route.this is object with no attributes
│     │ var.routes is map of object with 2 elements
│
│ Call to function "zipmap" failed: number of keys (2) does not match number of values (0).

**Comment by adammontlake** [comment]
Hey @yrachakonda 

1. Note that the terraform command you posted is not a refresh, just a regular plan
2. Please include all the technical details and steps to reproduce the error including the terraform code.

**Comment by adammontlake** [comment]
@yrachakonda 
Please share the required information.

**Comment by adammontlake** [comment]
Hey @yrachakonda 
Please take a moment to upload all the required information for us to help, without it we cannot debug the issue

**Comment by adammontlake** [comment]
Hey @yrachakonda 
Closing this issue, feel free to re-open.
